language: node_js
cache:
  directories:
    - ~/.npm
dist: trusty
sudo: required
notifications:
  email: false
node_js: 10
addons:
  chrome: stable
script: "echo 'Test disabled'"
branches:
  only:
    - master
deploy:
  provider: script
  on:
    branch: master
  skip_cleanup: true
  script:
    - npx semantic-release --branch master